# Default Configuration
safe:        true
auto:        false
server:      false
server_port: 4000
# baseurl: /
baseurl : /
# baseurl:    http://uwin.hk
permalink: /:categories/:title.html

# url: http://localhost:4000
# url:  http://uwin.hk
url : http://uwinhk.github.com

source:      .
destination: ./_site
plugins:     ./_plugins
